version: '3.9'

services:
  web:
    build: .
    restart: always
    environment:
      DATABASE_URL: host=db port=5432 user=postgres password=postgres dbname=postgres sslmode=disable
    ports:
      - 3002:3001
    depends_on:
      - db
    volumes:
      - ./keys:/out/keys
      - ./views:/out/views

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
